packages:
  - 'apps/*'
  - 'packages/*'
  - 'backend'
allowBuilds:
  bufferutil: true
  electron: true
  es5-ext: true
  esbuild: true
  phantomjs-prebuilt: false
  sharp: false
  utf-8-validate: true
